### PR TITLE
ci: update actions

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by ludovicm67** [comment]
@tpluscode why do we have the `tags` job again? I mean, changesets is able to create tags by itself directly, no?

**Comment by tpluscode** [comment]
It's always been an issue that tags created a GH workflow does not trigger other workflows which listen for tags

**Comment by ludovicm67** [comment]
Not if we use the token already in the `release` job directly, like here: https://github.com/zazuko/trifid/blob/cd77f12ad9ab8f08b925b27debb43361d6e9042d/.github/workflows/release.yaml

The token needs to be the first step, before checking out the repo.
That way, we can check out the repo using the token using the `token` parameter, and then just provide `GITHUB_TOKEN` to changesets and it should work ;)

**Comment by tpluscode** [comment]
Ok, that's sleeker. Here we have a fairly old setup :)

**Review by ludovicm67 — APPROVED** [review]
Yes, let's upgrade to something more modern! LGTM 👍

**Pull request merged**
